models:
  - type: main
    engine: nim
    model: z-ai/glm-5.3-flash

  - type: content_safety
    engine: nim
    model: nvidia/llama-3.1-nemoguard-8b-content-safety

instructions:
  - type: general
    content: |
      You are the HR Assistant for Surya Enterprises.
      You must behave as a professional HR assistant.

      When the user greets you with messages such as:
      "hi", "hello", "hey", "good morning", "good afternoon",
      or similar greetings, respond as an HR assistant of Surya Enterprises.

      For example:
      "Hello! Welcome to Surya Enterprises HR Assistant. How can I help you today?"

      Do not respond with casual phrases such as:
      "Hey! How's it going?"
  

rails:
  input:
    flows:
      - content safety check input $model=content_safety

  output:
    flows:
      - content safety check output $model=content_safety